version: "3.7"

services:
  elquintosolmarketing.com:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: elquintosolmarketing.com
    restart: always
    networks:
      - npm
      - elquintosolmarketing.com-net

networks:
  elquintosolmarketing.com-net:
    name: elquintosolmarketing.com-net
    driver: bridge
  npm:
    external: true